# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d4e8c56943345371db234b4ccd2b9999dec0e9e07d9d95c187c737582df93d3429bf053ad6788c90b2e36ad9248f0739d06f865eec7d9337b98f9551b103b9f

test:
  secret_key_base: e3c7c427a40da8b5d891bd791288fd466321fcf7a9e8a0c640f6f2b49741130b81ed39682c16c884b238269782f67fc87a3832e3b03084b5a736c8ab9ee32ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
